##############################
# ui_tab_pelagics_controlbar.R
#
# 
# 
##############################

fluidRow(
  bs4Dash::bs4Card(title = "TYPE DE PRÉDICTION", 
                   id = "pelagic_type_prediction_card",
                   status = "navy", 
                   solidHeader = TRUE, 
                   collapsible = TRUE, 
                   collapsed = FALSE, 
                   width = 12,
                   icon = icon("cogs"), 
                   maximizable = FALSE, 
                   div(class = "left-text",
                       radioButtons(inputId = "prediction_type_ID", 
                                    label = NULL, 
                                    choiceNames = c("CPUE","PRODUCTION"),
                                    choiceValues = c("cpue","catch"), 
                                    inline = TRUE, 
                                    selected = "cpue")
                       )
                   ),
  # bs4Dash::bs4Card(title = "CRÉER SIMULATION", 
  #                  id = "pelagic_new_or_old_simulation_card",
  #                  status = "navy", 
  #                  solidHeader = TRUE, 
  #                  collapsible = TRUE, 
  #                  collapsed = FALSE, 
  #                  width = 12,
  #                  icon = icon("cogs"), 
  #                  maximizable = FALSE, 
  #                  div(class = "left-text",
  #                      radioButtons(inputId = "new_old_sim_ID", 
  #                                   label = NULL, 
  #                                   choiceNames = c("Nouvelle","Enregistrée"),
  #                                   choiceValues = c("new_sim","old_sim"), 
  #                                   inline = TRUE, 
  #                                   selected = "new_sim"),
  #                      hr(),
  #                      selectInput(inputId = "select_saved_simulation_ID", 
  #                                  label = "Simulations Enregistrées", 
  #                                  choices = NULL, 
  #                                  selected = "", 
  #                                  multiple = FALSE)
  #                      )
  #                  ),
  bs4Dash::bs4Card(title = "SCENARIO DE L'EFFORT DE PÊCHE", 
                   id = "pelagic_fishing_effort_scenario_card",
                   status = "navy", 
                   solidHeader = TRUE, 
                   collapsible = TRUE, 
                   collapsed = FALSE, 
                   width = 12,
                   icon = icon("cogs"), 
                   maximizable = FALSE, 
                   div(class = "text-left",
                       sliderInput(inputId = "slider_wgt_env_ID", 
                                   "Poids de l'environnement", 
                                   min = 0, 
                                   max = 100, 
                                   value = 100, 
                                   step=1),
                       hr(),
                       sliderInput(inputId = "slider_wgt_dist_ID", 
                                   label = "Poids de la distance du port", 
                                   min = 0,  
                                   max = 100, 
                                   value = 100),
                       hr(),
                       sliderInput(inputId = "slider_wgt_hist_ID",
                                   label = "Poids de l'historique", 
                                   min = 0, 
                                   max = 100, 
                                   value = 100),
                       hr(),
                       radioButtons(inputId = "direction_ID", 
                                    label = "Direction de préférence", 
                                    choiceNames = c("Sud de Dakhla", "Nord de Dakhla"),
                                    choiceValues = c("sud_dakhla","nord_dakhla"),
                                    inline = TRUE, 
                                    width = "100%")
                       )
                   ),
  
  bs4Card(title = "SIMULATION DE L'EFFORT DE PÊCHE", 
          id = "pelagic_fishing_effort_simulation_catch_card",
          status = "navy", 
          solidHeader = TRUE, 
          collapsible = TRUE, 
          collapsed = FALSE, 
          width = 12,
          icon = icon("cogs"), 
          maximizable = FALSE, 
          div(class = "text-left",
              selectInput(inputId = "catch_simulation_year_ID", 
                          label = "Année de simulation", 
                          choices = (as.numeric(format(Sys.Date(), "%Y"))+1):2016, 
                          selected = (as.numeric(format(Sys.Date(), "%Y"))), 
                          multiple = F),
              selectizeInput(inputId = "catch_simulation_months_ID", 
                             label = "Mois de simulation", 
                             choices =c("Janvier"=1,"Février"=2,"Mars"=3, 
                                        "Avril"=4,"Mai"=5,"Juin"=6,
                                        "Juillet"=7,"Août"=8,"Septembre"=9,
                                        "Octobre"=10,"Novembre"=11,"Décembre"=12),
                             multiple =T,selected = 1,options = list(maxItems = 6)),
              selectInput(inputId = "catch_year_to_simulate_from_ID", 
                          label = "Année de reférence pour simulation", 
                          choices = c("Mean(All)",2019,2018,2017,2016,2015,2014), 
                          selected = 1, 
                          multiple = F),
              hr(),
              radioButtons(inputId = "rb_main_species_ID",label = "Espèce cible" ,choiceNames = c("Sardine","Maquereau","Chinchard"), 
                           choiceValues = c("Sardina_pilchardus","Scomber_colias","Trachurus_trachurus"),inline = TRUE),
              br(),
              useShinyalert(),  
              actionButton(inputId= "btn_simulate_effort_ID", 
                           label = "Simulation",
                           status = "success",
                           flat =TRUE ,
                           width = "100%",
                           icon = icon("random",lib = "font-awesome"))
              # splitLayout(cellWidths = c("40%", "60%"),
              #             actionButton(inputId= "btn_simulate_effort_ID", 
              #                          label = "Simuler Effort",
              #                          status = "success",
              #                          flat =TRUE ,
              #                          width = "100%",
              #                          icon = icon("random",lib = "font-awesome")),
              #             actionButton(inputId = "btn_save_effort_ID", 
              #                          label = "Enregistrer Simulation", color = "primary",
              #                          status = "primary",
              #                          flat =TRUE ,
              #                          width = "100%",
              #                          icon = icon("save",lib = "font-awesome"))
              #             )
              )
          ),
  bs4Card(title = "SIMULATION DE L'EFFORT DE PÊCHE", 
          id = "pelagic_fishing_effort_simulation_cpues_card",
          status = "navy", 
          solidHeader = TRUE, 
          collapsible = TRUE, 
          collapsed = FALSE, 
          width = 12,
          icon = icon("cogs"), 
          maximizable = FALSE, 
          div(class = "text-left",
              selectInput(inputId = "cpue_simulation_year_ID", 
                          label = "Année de simulation", 
                          choices = (as.numeric(format(Sys.Date(), "%Y"))+1):2016, 
                          selected = (as.numeric(format(Sys.Date(), "%Y"))), 
                          multiple = F),
              selectizeInput(inputId = "cpue_simulation_months_ID", 
                             label = "Mois de simulation", 
                             choices =c("Janvier"=1,"Février"=2,"Mars"=3, 
                                        "Avril"=4,"Mai"=5,"Juin"=6,
                                        "Juillet"=7,"Août"=8,"Septembre"=9,
                                        "Octobre"=10,"Novembre"=11,"Décembre"=12),
                             multiple =T,selected = 1,options = list(maxItems = 6))
              )
          ),
  bs4Card(title = "PRÉDICTION DE LA PÊCHE", 
          id = "pelagic_fishing_catch_simulation_card",
          status = "navy", 
          solidHeader = TRUE, 
          collapsible = TRUE, 
          collapsed = FALSE, 
          width = 12,
          icon = icon("cogs"), 
          maximizable = FALSE, 
          div(class = "text-left",
              checkboxGroupInput(inputId = "species_ID",
                                 label = "Especes",
                                 selected = c("Sardina_pilchardus","Scomber_colias","Trachurus_trachurus"),
                                 inline = TRUE,
                                 choiceNames = c("Sardine","Maquereau", "Chinchard"),
                                 choiceValues = c("Sardina_pilchardus","Scomber_colias","Trachurus_trachurus")
              )
          ),
          div(class = "text-left",
              numericInput(inputId = "sardine_last_month_catch_ID", 
                           label = "Capture du dernier mois en Sardine (t)", 
                           value = 0,min = 0,max = 1000000,step = 1),
              numericInput(inputId = "maquereau_last_month_catch_ID", 
                           label = "Capture du dernier mois en Maquereau (t)",
                           value = 0,min = 0,max = 1000000,step = 1),
              numericInput(inputId = "chinchard_last_month_catch_ID",
                           label = "Capture du dernier mois en Chinchard (t)",
                           value = 0,min = 0,max = 1000000,step = 1),
              hr(),
              useShinyalert(),  
              actionButton(inputId= "btn_run_fishing_prediction_ID", 
                           label = "Prédiction",
                           status = "success",
                           flat =TRUE ,width = "100%",
                           icon = icon("random",lib = "font-awesome"))
          )
  )
)




